# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: harness/api/api.proto for package 'temporal.omes.projects.v1'

require 'grpc'
require 'harness/api/api_pb'

module Temporal
  module Omes
    module Projects
      module V1
        module ProjectService
          # ProjectService is the gRPC interface used by omes to intialize and drive load to
          # a project.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'temporal.omes.projects.v1.ProjectService'

            # Init creates a Temporal client, runs project-specific setup, and prepares for execution.
            rpc :Init, ::Temporal::Omes::Projects::V1::InitRequest, ::Temporal::Omes::Projects::V1::InitResponse
            # Execute runs a single test iteration (e.g., start a workflow and verify the result).
            rpc :Execute, ::Temporal::Omes::Projects::V1::ExecuteRequest, ::Temporal::Omes::Projects::V1::ExecuteResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
