#!/usr/bin/env fish

# Fetches OMES config from a running cluster and writes config.fish
# Usage: fetch-config.fish <cell-id>

if test (count $argv) -lt 1
    echo "Usage: fetch-config.fish <cell-id>"
    exit 1
end

set -l cell $argv[1]
set script_dir (dirname (status --current-filename))

echo "Fetching deployment from $cell..."
set -l deploy_yaml (omni kubectl --context $cell get deployment -n omes -l app.kubernetes.io/instance=omes -o yaml 2>&1)
if test $status -ne 0
    echo "Error: failed to get deployment"
    echo $deploy_yaml
    exit 1
end

set -l image (echo "$deploy_yaml" | yq '.items[0].spec.template.spec.containers[0].image')
set -l registry (echo $image | string replace -r ':[^:]+$' '')
set -l tag (echo $image | string replace -r '^.*:' '')
set -l args (echo "$deploy_yaml" | yq -o=json '.items[0].spec.template.spec.containers[0].args')

set -l ns (echo $args | yq '.[] | select(test("--namespace="))' | string replace '--namespace=' '' | string replace '.e2e' '')
set -l scenario (echo $args | yq '.[] | select(test("--scenario="))' | string replace '--scenario=' '')
set -l runid (echo $args | yq '.[] | select(test("--run-id="))' | string replace '--run-id=cicd-go-' '')

set -l config_path "$script_dir/config.fish"

echo "Writing config to $config_path:"
echo ""
echo "  cell:              $cell"
echo "  ns:                $ns"
echo "  scenario:          $scenario"
echo "  runid:             $runid"
echo "  omes_image_tag:    $tag"
echo "  omes_ecr_registry: $registry"
echo ""
echo "Do you want to proceed? (y/n)"
read -l confirm

if test "$confirm" = "y" -o "$confirm" = "Y"
    echo "# Configuration for OMES worker and executor scripts
# Generated by fetch-config.fish from cell $cell

set -x cell \"$cell\"
set -x ns \"$ns\"
set -x runid \"$runid\"
set -x scenario \"$scenario\"
set -x omes_image_tag \"$tag\"

# ECR registry for OMES images
set -x omes_ecr_registry \"$registry\"" > $config_path
    echo "Config written."
else
    echo "Cancelled."
    exit 0
end
