# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: harness/api/api.proto

require 'google/protobuf'


descriptor_data = "\n\x15harness/api/api.proto\x12\x19temporal.omes.projects.v1\"\xcd\x01\n\x0e\x43onnectOptions\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x16\n\x0eserver_address\x18\x02 \x01(\t\x12\x13\n\x0b\x61uth_header\x18\x03 \x01(\t\x12\x12\n\nenable_tls\x18\x04 \x01(\x08\x12\x15\n\rtls_cert_path\x18\x05 \x01(\t\x12\x14\n\x0ctls_key_path\x18\x06 \x01(\t\x12\x17\n\x0ftls_server_name\x18\x07 \x01(\t\x12!\n\x19\x64isable_host_verification\x18\x08 \x01(\x08\"\xa0\x01\n\x0bInitRequest\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x12\n\ntask_queue\x18\x03 \x01(\t\x12\x42\n\x0f\x63onnect_options\x18\x04 \x01(\x0b\x32).temporal.omes.projects.v1.ConnectOptions\x12\x13\n\x0b\x63onfig_json\x18\x05 \x01(\x0c\"\x0e\n\x0cInitResponse\"H\n\x0e\x45xecuteRequest\x12\x11\n\titeration\x18\x01 \x01(\x03\x12\x12\n\ntask_queue\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"\x11\n\x0f\x45xecuteResponse2\xcf\x01\n\x0eProjectService\x12Y\n\x04Init\x12&.temporal.omes.projects.v1.InitRequest\x1a\'.temporal.omes.projects.v1.InitResponse\"\x00\x12\x62\n\x07\x45xecute\x12).temporal.omes.projects.v1.ExecuteRequest\x1a*.temporal.omes.projects.v1.ExecuteResponse\"\x00\x42<Z:github.com/temporalio/omes/workers/go/projects/harness/apib\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Temporal
  module Omes
    module Projects
      module V1
        ConnectOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("temporal.omes.projects.v1.ConnectOptions").msgclass
        InitRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("temporal.omes.projects.v1.InitRequest").msgclass
        InitResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("temporal.omes.projects.v1.InitResponse").msgclass
        ExecuteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("temporal.omes.projects.v1.ExecuteRequest").msgclass
        ExecuteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("temporal.omes.projects.v1.ExecuteResponse").msgclass
      end
    end
  end
end
