// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: harness/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Connection options passed from the CLI to the project-server during Init.
// These fields intentionally mirror the supported Omes client options used for
// connecting workers and scenarios today.
type ConnectOptions struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Namespace               string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServerAddress           string                 `protobuf:"bytes,2,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	AuthHeader              string                 `protobuf:"bytes,3,opt,name=auth_header,json=authHeader,proto3" json:"auth_header,omitempty"`
	EnableTls               bool                   `protobuf:"varint,4,opt,name=enable_tls,json=enableTls,proto3" json:"enable_tls,omitempty"`
	TlsCertPath             string                 `protobuf:"bytes,5,opt,name=tls_cert_path,json=tlsCertPath,proto3" json:"tls_cert_path,omitempty"`
	TlsKeyPath              string                 `protobuf:"bytes,6,opt,name=tls_key_path,json=tlsKeyPath,proto3" json:"tls_key_path,omitempty"`
	TlsServerName           string                 `protobuf:"bytes,7,opt,name=tls_server_name,json=tlsServerName,proto3" json:"tls_server_name,omitempty"`
	DisableHostVerification bool                   `protobuf:"varint,8,opt,name=disable_host_verification,json=disableHostVerification,proto3" json:"disable_host_verification,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConnectOptions) Reset() {
	*x = ConnectOptions{}
	mi := &file_harness_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectOptions) ProtoMessage() {}

func (x *ConnectOptions) ProtoReflect() protoreflect.Message {
	mi := &file_harness_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectOptions.ProtoReflect.Descriptor instead.
func (*ConnectOptions) Descriptor() ([]byte, []int) {
	return file_harness_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectOptions) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConnectOptions) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ConnectOptions) GetAuthHeader() string {
	if x != nil {
		return x.AuthHeader
	}
	return ""
}

func (x *ConnectOptions) GetEnableTls() bool {
	if x != nil {
		return x.EnableTls
	}
	return false
}

func (x *ConnectOptions) GetTlsCertPath() string {
	if x != nil {
		return x.TlsCertPath
	}
	return ""
}

func (x *ConnectOptions) GetTlsKeyPath() string {
	if x != nil {
		return x.TlsKeyPath
	}
	return ""
}

func (x *ConnectOptions) GetTlsServerName() string {
	if x != nil {
		return x.TlsServerName
	}
	return ""
}

func (x *ConnectOptions) GetDisableHostVerification() bool {
	if x != nil {
		return x.DisableHostVerification
	}
	return false
}

// Sent once at the start of a test run to initialize the project-server.
type InitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId    string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	RunId          string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskQueue      string                 `protobuf:"bytes,3,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	ConnectOptions *ConnectOptions        `protobuf:"bytes,4,opt,name=connect_options,json=connectOptions,proto3" json:"connect_options,omitempty"`
	// Optional JSON project configuration, passed from --option project-config-file
	// to the project's OnInit callback. Schema is project-defined.
	ConfigJson    []byte `protobuf:"bytes,5,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_harness_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_harness_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *InitRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *InitRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *InitRequest) GetConnectOptions() *ConnectOptions {
	if x != nil {
		return x.ConnectOptions
	}
	return nil
}

func (x *InitRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_harness_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_harness_api_api_proto_rawDescGZIP(), []int{2}
}

// Sent once per iteration. The project-server starts workflows and
// verifies results within the Execute handler.
type ExecuteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Iteration int64                  `protobuf:"varint,1,opt,name=iteration,proto3" json:"iteration,omitempty"`
	TaskQueue string                 `protobuf:"bytes,2,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	// Reserved for future executor-specific per-iteration data.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_harness_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_harness_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetIteration() int64 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *ExecuteRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *ExecuteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_harness_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_harness_api_api_proto_rawDescGZIP(), []int{4}
}

var File_harness_api_api_proto protoreflect.FileDescriptor

const file_harness_api_api_proto_rawDesc = "" +
	"\n" +
	"\x15harness/api/api.proto\x12\x19temporal.omes.projects.v1\"\xbf\x02\n" +
	"\x0eConnectOptions\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12%\n" +
	"\x0eserver_address\x18\x02 \x01(\tR\rserverAddress\x12\x1f\n" +
	"\vauth_header\x18\x03 \x01(\tR\n" +
	"authHeader\x12\x1d\n" +
	"\n" +
	"enable_tls\x18\x04 \x01(\bR\tenableTls\x12\"\n" +
	"\rtls_cert_path\x18\x05 \x01(\tR\vtlsCertPath\x12 \n" +
	"\ftls_key_path\x18\x06 \x01(\tR\n" +
	"tlsKeyPath\x12&\n" +
	"\x0ftls_server_name\x18\a \x01(\tR\rtlsServerName\x12:\n" +
	"\x19disable_host_verification\x18\b \x01(\bR\x17disableHostVerification\"\xdb\x01\n" +
	"\vInitRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x03 \x01(\tR\ttaskQueue\x12R\n" +
	"\x0fconnect_options\x18\x04 \x01(\v2).temporal.omes.projects.v1.ConnectOptionsR\x0econnectOptions\x12\x1f\n" +
	"\vconfig_json\x18\x05 \x01(\fR\n" +
	"configJson\"\x0e\n" +
	"\fInitResponse\"g\n" +
	"\x0eExecuteRequest\x12\x1c\n" +
	"\titeration\x18\x01 \x01(\x03R\titeration\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x02 \x01(\tR\ttaskQueue\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x11\n" +
	"\x0fExecuteResponse2\xcf\x01\n" +
	"\x0eProjectService\x12Y\n" +
	"\x04Init\x12&.temporal.omes.projects.v1.InitRequest\x1a'.temporal.omes.projects.v1.InitResponse\"\x00\x12b\n" +
	"\aExecute\x12).temporal.omes.projects.v1.ExecuteRequest\x1a*.temporal.omes.projects.v1.ExecuteResponse\"\x00B<Z:github.com/temporalio/omes/workers/go/projects/harness/apib\x06proto3"

var (
	file_harness_api_api_proto_rawDescOnce sync.Once
	file_harness_api_api_proto_rawDescData []byte
)

func file_harness_api_api_proto_rawDescGZIP() []byte {
	file_harness_api_api_proto_rawDescOnce.Do(func() {
		file_harness_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_harness_api_api_proto_rawDesc), len(file_harness_api_api_proto_rawDesc)))
	})
	return file_harness_api_api_proto_rawDescData
}

var file_harness_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_harness_api_api_proto_goTypes = []any{
	(*ConnectOptions)(nil),  // 0: temporal.omes.projects.v1.ConnectOptions
	(*InitRequest)(nil),     // 1: temporal.omes.projects.v1.InitRequest
	(*InitResponse)(nil),    // 2: temporal.omes.projects.v1.InitResponse
	(*ExecuteRequest)(nil),  // 3: temporal.omes.projects.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 4: temporal.omes.projects.v1.ExecuteResponse
}
var file_harness_api_api_proto_depIdxs = []int32{
	0, // 0: temporal.omes.projects.v1.InitRequest.connect_options:type_name -> temporal.omes.projects.v1.ConnectOptions
	1, // 1: temporal.omes.projects.v1.ProjectService.Init:input_type -> temporal.omes.projects.v1.InitRequest
	3, // 2: temporal.omes.projects.v1.ProjectService.Execute:input_type -> temporal.omes.projects.v1.ExecuteRequest
	2, // 3: temporal.omes.projects.v1.ProjectService.Init:output_type -> temporal.omes.projects.v1.InitResponse
	4, // 4: temporal.omes.projects.v1.ProjectService.Execute:output_type -> temporal.omes.projects.v1.ExecuteResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_harness_api_api_proto_init() }
func file_harness_api_api_proto_init() {
	if File_harness_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_harness_api_api_proto_rawDesc), len(file_harness_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_harness_api_api_proto_goTypes,
		DependencyIndexes: file_harness_api_api_proto_depIdxs,
		MessageInfos:      file_harness_api_api_proto_msgTypes,
	}.Build()
	File_harness_api_api_proto = out.File
	file_harness_api_api_proto_goTypes = nil
	file_harness_api_api_proto_depIdxs = nil
}
