name: Build & publish Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_to_docker_hub:
    runs-on: ubuntu-latest

    env:
      DOCKER_TAG: ${{ github.ref_name }}

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump Input context
        id: input_context_step
        run: echo '${{ toJSON(inputs) }}'

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta (Golang)
        id: meta_go
        uses: docker/metadata-action@v3
        with:
          images: temporaliotest/omes
          tags: |
            type=sha,format=short,event=branch
            latest-go

      - name: Build and push (Golang)
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_go.outputs.tags }}
          labels: ${{ steps.meta_go.outputs.labels }}
          file: dockerfiles/go.Dockerfile
          context: .
